#!/usr/bin/env python3
"""Build curated audio pack configs from quality-report recommendations.

Reads:
  reports/audio-pack-quality-report.md (reference)
  src/generated/audioPacks/trancePack1.ts
  src/generated/audioPacks/beatsBoxPack1.ts

Writes:
  src/generated/audioPacks/tranceCuratedPack1.ts
  src/generated/audioPacks/beatsBoxCuratedPack1.ts

Run:
  python3 tools/build_curated_packs.py
"""

from __future__ import annotations

import re
from dataclasses import dataclass
from pathlib import Path
PROJECT_ROOT = Path(__file__).resolve().parents[1]
REPORT_PATH = PROJECT_ROOT / "reports" / "audio-pack-quality-report.md"
TRANCE_SOURCE = PROJECT_ROOT / "src" / "generated" / "audioPacks" / "trancePack1.ts"
BEATS_SOURCE = PROJECT_ROOT / "src" / "generated" / "audioPacks" / "beatsBoxPack1.ts"
TRANCE_OUT = PROJECT_ROOT / "src" / "generated" / "audioPacks" / "tranceCuratedPack1.ts"
BEATS_OUT = PROJECT_ROOT / "src" / "generated" / "audioPacks" / "beatsBoxCuratedPack1.ts"

SlotRole = str

TRANCE_CURATED: list[tuple[str, SlotRole]] = [
    ("bass-2.wav", "foundation"),
    ("bass-3.wav", "rhythm"),
    ("melody-3.wav", "melody"),
    ("melody-6.wav", "melodySupport"),
    ("melody-9.wav", "texture"),
    ("melody-7.wav", "accent"),
    ("melody-16.wav", "spare"),
]

BEATS_CURATED: list[tuple[str, SlotRole]] = [
    ("beat-11.wav", "foundation"),
    ("beat-4.wav", "rhythm"),
    ("beat-7.wav", "melody"),
    ("melody-2.wav", "melodySupport"),
    ("melody-3.wav", "texture"),
    ("beat-12.wav", "accent"),
    ("voice-1.wav", "spare"),
]


@dataclass
class TrancePad:
    id: str
    category: str
    label: str
    source_file: str
    audio_file: str
    audio_path: str
    duration_seconds: float


@dataclass
class BeatsPad:
    id: str
    category: str
    filename: str
    audio_path: str
    duration: float
    bpm: float
    original_filename: str


def parse_trance_packs(text: str) -> dict[str, TrancePad]:
    blocks = re.split(r"\n  \{", text)
    pads: dict[str, TrancePad] = {}
    for block in blocks:
        audio = re.search(r'audioFile:\s*"([^"]+)"', block)
        if not audio:
            continue
        filename = audio.group(1)
        pads[filename] = TrancePad(
            id=require(block, r'id:\s*"([^"]+)"'),
            category=require(block, r'category:\s*"([^"]+)"'),
            label=require(block, r'label:\s*"([^"]+)"'),
            source_file=require(block, r'sourceFile:\s*"([^"]+)"'),
            audio_file=filename,
            audio_path=require(block, r'audioPath:\s*"([^"]+)"'),
            duration_seconds=float(require(block, r"durationSeconds:\s*([0-9.]+)")),
        )
    return pads


def parse_beats_packs(text: str) -> dict[str, BeatsPad]:
    blocks = re.split(r"\n  \{", text)
    pads: dict[str, BeatsPad] = {}
    for block in blocks:
        filename_match = re.search(r'filename:\s*"([^"]+)"', block)
        if not filename_match:
            continue
        filename = filename_match.group(1)
        pads[filename] = BeatsPad(
            id=require(block, r'id:\s*"([^"]+)"'),
            category=require(block, r'category:\s*"([^"]+)"'),
            filename=filename,
            audio_path=require(block, r'audioPath:\s*"([^"]+)"'),
            duration=float(require(block, r"duration:\s*([0-9.]+)")),
            bpm=float(require(block, r"bpm:\s*([0-9.]+)")),
            original_filename=require(block, r'originalFilename:\s*"([^"]+)"'),
        )
    return pads


def require(text: str, pattern: str) -> str:
    match = re.search(pattern, text)
    if not match:
        raise ValueError(f"Missing {pattern!r} in pad block")
    return match.group(1)


def slot_category(role: SlotRole, source_category: str) -> str:
    """Gameplay category for a curated slot (maps to UI pad row)."""
    if role == "foundation":
        return "bass" if source_category == "bass" else "beat"
    if role == "rhythm":
        return "bass" if source_category == "bass" else "beat"
    if role in {"melody", "melodySupport"}:
        return "melody"
    if role == "texture":
        return "fx" if source_category == "fx" else "melody"
    if role == "accent":
        return "voice" if source_category == "voice" else "beat"
    return source_category


def render_trance_curated(pads_by_file: dict[str, TrancePad], curated: list[tuple[str, SlotRole]]) -> str:
    lines = [
        "/* Auto-generated by tools/build_curated_packs.py. Do not edit by hand. */",
        "",
        "export type CuratedSlotRole =",
        "  | 'foundation'",
        "  | 'rhythm'",
        "  | 'melody'",
        "  | 'melodySupport'",
        "  | 'texture'",
        "  | 'accent'",
        "  | 'spare'",
        "",
        "export type CuratedTranceCategory = 'beat' | 'bass' | 'melody' | 'fx' | 'voice'",
        "",
        "export type CuratedTrancePadConfig = {",
        "  id: string",
        "  category: CuratedTranceCategory",
        "  slotRole: CuratedSlotRole",
        "  slotIndex: number",
        "  label: string",
        "  sourceFile: string",
        "  audioFile: string",
        "  audioPath: string",
        "  order: number",
        "  durationSeconds: number",
        "}",
        "",
        "export const tranceCuratedPack1 = {",
        '  id: "trance-curated-pack-1",',
        '  name: "Trance Curated Pack 1",',
        "  sourcePackId: \"trance-pack-1\",",
        "  bpm: 100,",
        "  loopSeconds: 9.6,",
        '  audioDirectory: "assets/audio/generated/trance-pack-1",',
        "  pads: [",
    ]

    for index, (filename, role) in enumerate(curated, start=1):
        pad = pads_by_file[filename]
        category = slot_category(role, pad.category)
        label = f"Curated {role.replace('melodySupport', 'Melody+')} {index}"
        lines.extend(
            [
                "  {",
                f'    id: "curated-{pad.id}",',
                f'    category: "{category}",',
                f'    slotRole: "{role}",',
                f"    slotIndex: {index},",
                f'    label: "{label}",',
                f'    sourceFile: "{pad.source_file}",',
                f'    audioFile: "{pad.audio_file}",',
                f'    audioPath: "{pad.audio_path}",',
                f"    order: {index},",
                f"    durationSeconds: {pad.duration_seconds:.6f},",
                "  },",
            ]
        )

    lines.extend(
        [
            "  ] satisfies CuratedTrancePadConfig[],",
            "} as const",
            "",
        ]
    )
    return "\n".join(lines)


def render_beats_curated(pads_by_file: dict[str, BeatsPad], curated: list[tuple[str, SlotRole]]) -> str:
    lines = [
        "/* Auto-generated by tools/build_curated_packs.py. Do not edit by hand. */",
        "",
        "export type CuratedBeatsSlotRole =",
        "  | 'foundation'",
        "  | 'rhythm'",
        "  | 'melody'",
        "  | 'melodySupport'",
        "  | 'texture'",
        "  | 'accent'",
        "  | 'spare'",
        "",
        "export type CuratedBeatsCategory = 'beat' | 'voice' | 'fx' | 'percussion' | 'melody' | 'bass'",
        "",
        "export type CuratedBeatsPadConfig = {",
        "  id: string",
        "  packId: string",
        "  packName: string",
        "  category: CuratedBeatsCategory",
        "  slotRole: CuratedBeatsSlotRole",
        "  slotIndex: number",
        "  filename: string",
        "  audioPath: string",
        "  duration: number",
        "  bpm: number",
        "  originalFilename: string",
        "  order: number",
        "}",
        "",
        "export const beatsBoxCuratedPack1 = {",
        '  id: "beats-box-curated-pack-1",',
        '  name: "Beats Box Curated Pack 1",',
        "  sourcePackId: \"beats-box-pack-1\",",
        "  bpm: 100,",
        "  loopSeconds: 9.6,",
        "  sampleRate: 44100,",
        '  audioDirectory: "assets/audio/generated/beats-box-pack-1",',
        "  pads: [",
    ]

    pack_id = "beats-box-curated-pack-1"
    pack_name = "Beats Box Curated Pack 1"

    for index, (filename, role) in enumerate(curated, start=1):
        pad = pads_by_file[filename]
        category = slot_category(role, pad.category)
        lines.extend(
            [
                "  {",
                f'    id: "curated-{pad.id}",',
                f'    packId: "{pack_id}",',
                f'    packName: "{pack_name}",',
                f'    category: "{category}",',
                f'    slotRole: "{role}",',
                f"    slotIndex: {index},",
                f'    filename: "{pad.filename}",',
                f'    audioPath: "{pad.audio_path}",',
                f"    duration: {pad.duration:.6f},",
                f"    bpm: {pad.bpm:.0f},",
                f'    originalFilename: "{pad.original_filename}",',
                f"    order: {index},",
                "  },",
            ]
        )

    lines.extend(
        [
            "  ] satisfies CuratedBeatsPadConfig[],",
            "} as const",
            "",
        ]
    )
    return "\n".join(lines)


def validate_selection(
    label: str,
    curated: list[tuple[str, SlotRole]],
    pads_by_file: dict[str, object],
) -> None:
    missing = [name for name, _ in curated if name not in pads_by_file]
    if missing:
        raise SystemExit(f"{label}: missing source loops: {', '.join(missing)}")


def main() -> None:
    if not REPORT_PATH.is_file():
        print(f"Note: report not found at {REPORT_PATH} (continuing with fixed selections)")

    trance_pads = parse_trance_packs(TRANCE_SOURCE.read_text(encoding="utf-8"))
    beats_pads = parse_beats_packs(BEATS_SOURCE.read_text(encoding="utf-8"))

    validate_selection("Trance curated", TRANCE_CURATED, trance_pads)
    validate_selection("Beats curated", BEATS_CURATED, beats_pads)

    TRANCE_OUT.write_text(render_trance_curated(trance_pads, TRANCE_CURATED), encoding="utf-8")
    BEATS_OUT.write_text(render_beats_curated(beats_pads, BEATS_CURATED), encoding="utf-8")

    print(f"Wrote {TRANCE_OUT.relative_to(PROJECT_ROOT)} ({len(TRANCE_CURATED)} pads)")
    print(f"Wrote {BEATS_OUT.relative_to(PROJECT_ROOT)} ({len(BEATS_CURATED)} pads)")
    print()
    print("Trance curated files:")
    for filename, role in TRANCE_CURATED:
        print(f"  [{role}] {filename}")
    print()
    print("Beats Box curated files:")
    for filename, role in BEATS_CURATED:
        print(f"  [{role}] {filename}")


if __name__ == "__main__":
    main()
